### ISSUE TITLE
Whitelist-request template omits usdcThroughIntegrator, the field WHITELISTING.md says is required (FIN 71)

### ISSUE THREAD

**Issue by gitchadd** [p2pdotme/payment-integrators#67]
`docs/WHITELISTING.md:44` lists `usdcThroughIntegrator` as a required field of the "Whitelist request" issue template:

> **`usdcThroughIntegrator`**: `true` or `false` -- pinned at registration. `true` routes BUY proceeds to the integrator on completion (e.g. LotPot); `false` routes direct to the order's `recipientAddr`. Must match what the integrator's `onOrderComplete` was coded to expect.

`.github/ISSUE_TEMPLATE/whitelist-request.md` has no such field. The only address-shaped field it asks for is `Pinned proxyImpl` at line 27.

So the person filing a whitelist request is never asked which routing mode their integrator expects, and the superAdmin running `registerIntegrator(integrator, usdcThroughIntegrator, proxyImpl)` picks the flag by reading PR prose.

That flag is load-bearing. `contracts-v4/contracts/facets/B2BGatewayFacet.sol:264-268` routes settlement to the integrator when it is true and to the buyer's `recipientAddr` when it is false. Getting it wrong on an integrator coded for `false` sends every buyer's proceeds to a contract that is not expecting them. It is also not a one-time risk: `B2BGatewayFacet.sol:126-133` allows the field to be re-asserted freely on any re-registration, with only `proxyImpl` set-once.

The review of #64 found that the integrator in that PR cannot detect the mistake from its callback arguments, so the filing template is currently the earliest point at which a wrong value could be caught.

Fix: add the field to the template, mirroring the wording already in `docs/WHITELISTING.md:44`. One line in one markdown file, no code surface.

Pre-existing, not introduced by #64. Surfaced by its review.

| SEC | UX | AUTO | YAGNI | DELTA | FIN |
|-----|----|------|-------|-------|-----|
|  55 | 10 |  95  |  85   |  95   | 71  |
